# Generated by Django 4.0.4 on 2022-10-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
        migrations.RemoveField(
            model_name='region',
            name='extra_short_name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='genitive',
        ),
        migrations.RemoveField(
            model_name='region',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='slug',
        ),
    ]
