# Generated by Django 4.0.4 on 2022-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_region_code_remove_region_extra_short_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='fullname_idx',
        ),
        migrations.RemoveField(
            model_name='person',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_from_rupep',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dissernet',
        ),
        migrations.RemoveField(
            model_name='person',
            name='duma_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='person',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='person',
            name='locked_page',
        ),
        migrations.RemoveField(
            model_name='person',
            name='redflag_index',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rupep',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rupep_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='person',
            name='vkontakte',
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['family_name', 'name', 'patronymic'], name='fullname_idx'),
        ),
    ]
