services:
  db:
    image: postgres:13
    env_file:
      - .env
    expose:
      - 5433
    ports:
      - 5433:5433
    command: -p 5433    
    restart: always

  web:
    build: 
      context: ./site
      dockerfile: ./MyDockerfile
    command: /bin/bash -c 'source init_app.sh'
    volumes:
      - ./site:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always
        
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

    