services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always

  web:
    build: 
      context: ./site
      dockerfile: ./MyDockerfile
    command: /bin/bash -c "sleep 999" #init_db.sh
    volumes:
      - ./site:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
        
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

    